export type BlogPost = {
  slug: string;
  title: string;
  excerpt: string;
  date: string;
  category: string;
  readTime: string;
  isPillar?: boolean;
  publishDate?: string;
};

export const BLOG_POSTS: BlogPost[] = [
  // --- PILARES SEO ---
  {
    slug: "como-mejorar-rentabilidad-empresa",
    title: "Cómo mejorar la rentabilidad de tu empresa — Guía completa para pymes",
    excerpt: "Guía pilar con todo lo que necesitas saber para mejorar la rentabilidad de tu pyme: márgenes, costes, precios, productividad, flujo de caja y un plan de acción paso a paso.",
    date: "10 abril 2025",
    category: "Rentabilidad",
    readTime: "18 min",
    isPillar: true,
  },
  {
    slug: "como-conseguir-clientes-para-tu-negocio",
    title: "Cómo conseguir más clientes para tu negocio — Guía completa de captación para pymes",
    excerpt: "Por qué falla la captación, canales reales, estrategia local vs digital, cómo crear un sistema estable, errores que tiran dinero y casos reales. Todo lo que una pyme necesita.",
    date: "10 abril 2025",
    category: "Clientes",
    readTime: "18 min",
    isPillar: true,
  },
  {
    slug: "indicadores-clave-de-una-empresa",
    title: "Qué números debe controlar cualquier empresa para no ir a ciegas — Guía completa de KPIs",
    excerpt: "Los 9 KPIs que toda pyme debe vigilar: margen, punto muerto, ticket medio, CAC, flujo de caja. Cómo interpretar datos, tomar decisiones con números reales y montar tu sistema de control mensual.",
    date: "10 abril 2025",
    category: "Control y gestión",
    readTime: "18 min",
    isPillar: true,
  },
  {
    slug: "como-organizar-empresa-pequena-salir-autoempleo",
    title: "Cómo organizar una empresa para que crezca (y dejar de ser esclavo de tu negocio) — Guía completa",
    excerpt: "Caos operativo, empresario autoempleado, procesos, delegación, sistemas simples, cómo liberar tiempo y preparar el crecimiento. Todo lo que una pyme necesita para dejar de depender del dueño.",
    date: "10 abril 2025",
    category: "Organización",
    readTime: "18 min",
    isPillar: true,
  },
  {
    slug: "como-hacer-crecer-una-empresa-pequena",
    title: "Cómo hacer crecer una empresa paso a paso — Guía completa de estrategia de crecimiento",
    excerpt: "Fases de crecimiento, errores al escalar, cuándo invertir, cuándo contratar, nuevas líneas de negocio, mentalidad empresarial y plan real de crecimiento para pymes.",
    date: "10 abril 2025",
    category: "Crecimiento",
    readTime: "18 min",
    isPillar: true,
  },
  {
    slug: "como-definir-estrategia-negocio",
    title: "Cómo definir la estrategia de tu negocio para dejar de improvisar — Guía completa",
    excerpt: "Modelo de negocio, propuesta de valor, posicionamiento, plan estratégico en una página, errores que cuestan dinero y revisión periódica. Todo lo que una pyme necesita para tener dirección.",
    date: "10 abril 2025",
    category: "Estrategia",
    readTime: "18 min",
    isPillar: true,
  },
  // --- ARTÍCULOS DE APOYO ---
  {
    slug: "por-que-no-funciona-la-publicidad-en-mi-negocio",
    title: "Por qué muchas empresas tiran el dinero en marketing (y cómo evitarlo)",
    excerpt: "Frustración con agencias, publicidad sin estrategia y dinero perdido. Descubre cómo saber si tu marketing funciona y un sistema práctico para evaluar cada euro que inviertes.",
    date: "13 marzo 2025",
    category: "Marketing",
    readTime: "12 min",
  },
  {
    slug: "como-diferenciarte-de-tu-competencia",
    title: "Cómo diferenciarte de tu competencia sin competir en precio",
    excerpt: "Si tu negocio ofrece lo mismo que los demás, compites por precio y pierdes margen. Descubre cómo encontrar tu ventaja competitiva real y posicionarte como la mejor opción.",
    date: "13 marzo 2025",
    category: "Estrategia",
    readTime: "13 min",
  },
  {
    slug: "como-fijar-precios-en-tu-negocio",
    title: "Cómo fijar precios en tu negocio sin perder clientes ni margen",
    excerpt: "La mayoría de pymes fijan precios por intuición o copiando a la competencia. Aprende métodos reales para calcular precios que cubran costes, generen beneficio y el cliente acepte.",
    date: "13 marzo 2025",
    category: "Rentabilidad",
    readTime: "14 min",
  },
  {
    slug: "problemas-de-liquidez-en-pymes",
    title: "Tu empresa factura pero no tiene dinero: cómo resolver los problemas de liquidez",
    excerpt: "Facturas pendientes, pagos que no cuadran y la cuenta siempre al límite. Causas reales de los problemas de liquidez en pymes y un plan práctico para resolverlos.",
    date: "13 marzo 2025",
    category: "Control y gestión",
    readTime: "13 min",
  },
  {
    slug: "como-tomar-decisiones-en-un-negocio",
    title: "Las decisiones que están frenando tu negocio (aunque no te des cuenta)",
    excerpt: "Soledad, miedo, decisiones emocionales y falta de claridad estratégica. Descubre qué bloquea a los empresarios y cómo aprender a pensar con método para desbloquear tu negocio.",
    date: "13 marzo 2025",
    category: "Estrategia",
    readTime: "13 min",
  },
  {
    slug: "como-mejorar-rentabilidad-restaurante-bar",
    title: "Cómo mejorar la rentabilidad de tu restaurante o bar sin subir precios",
    excerpt: "Escandallos, costes ocultos, turnos, carta y proveedores. Guía práctica para que tu restaurante o bar gane más dinero optimizando lo que ya tienes.",
    date: "13 marzo 2025",
    category: "Rentabilidad",
    readTime: "14 min",
  },
  {
    slug: "cuando-contratar-un-consultor-de-negocios",
    title: "¿Cuándo merece la pena contratar un consultor de negocios?",
    excerpt: "Señales claras de que tu negocio necesita una mirada externa, qué esperar de una consultoría, cuánto cuesta y cómo elegir al consultor adecuado sin tirar el dinero.",
    date: "13 marzo 2025",
    category: "Estrategia",
    readTime: "12 min",
  },
  {
    slug: "por-que-tu-empresa-factura-pero-no-gana-dinero",
    title: "Por qué tu empresa factura pero no gana dinero",
    excerpt: "Errores habituales que destruyen la rentabilidad de las pymes, cómo calcular si tu negocio realmente gana dinero y decisiones que mejoran los beneficios rápidamente.",
    date: "13 marzo 2025",
    category: "Rentabilidad",
    readTime: "12 min",
  },
  // --- ARTÍCULOS LONG TAIL (publicación programada) ---
  {
    slug: "como-reducir-gastos-empresa-sin-recortar",
    title: "Cómo reducir gastos en tu empresa sin recortar en lo que importa",
    excerpt: "7 áreas donde las pymes malgastan dinero y cómo optimizar gastos sin cargarte la calidad ni el crecimiento.",
    date: "21 abril 2025",
    category: "Rentabilidad",
    readTime: "10 min",
    publishDate: "2025-04-21",
  },
  {
    slug: "mi-negocio-no-crece-que-hago",
    title: "Mi negocio no crece: qué hacer cuando te estancas",
    excerpt: "Señales de estancamiento, causas reales y 5 acciones concretas para salir del bloqueo y volver a crecer.",
    date: "24 abril 2025",
    category: "Crecimiento",
    readTime: "10 min",
    publishDate: "2025-04-24",
  },
  {
    slug: "cuanto-debe-ganar-el-dueno-de-un-negocio",
    title: "Cuánto debe ganar el dueño de un negocio: la pregunta incómoda",
    excerpt: "Muchos empresarios cobran menos que sus empleados. Cómo calcular tu sueldo justo y separar beneficio de compensación.",
    date: "5 mayo 2025",
    category: "Rentabilidad",
    readTime: "10 min",
    publishDate: "2025-05-05",
  },
  {
    slug: "como-delegar-tareas-sin-perder-control",
    title: "Cómo delegar tareas en tu empresa sin perder el control",
    excerpt: "Por qué no delegas, qué te cuesta no hacerlo, qué delegar primero y cómo montar un sistema de delegación real.",
    date: "19 mayo 2025",
    category: "Organización",
    readTime: "10 min",
    publishDate: "2025-05-19",
  },
  {
    slug: "como-calcular-margen-beneficio-producto",
    title: "Cómo calcular el margen de beneficio de un producto o servicio",
    excerpt: "Margen bruto vs neto, fórmulas claras, los costes que nadie incluye y qué hacer cuando un producto tiene margen negativo.",
    date: "2 junio 2025",
    category: "Rentabilidad",
    readTime: "10 min",
    publishDate: "2025-06-02",
  },
  {
    slug: "como-fidelizar-clientes-pyme",
    title: "Cómo fidelizar clientes en una pyme: estrategias que funcionan",
    excerpt: "Retener clientes cuesta 5 veces menos que conseguir nuevos. Estrategias prácticas de fidelización para pymes.",
    date: "16 junio 2025",
    category: "Clientes",
    readTime: "10 min",
    publishDate: "2025-06-16",
  },
  {
    slug: "errores-empresarios-pyme-mas-comunes",
    title: "Los 10 errores más comunes de los empresarios pyme",
    excerpt: "Los fallos de gestión que frenan a la mayoría de pymes. Identificarlos es el primer paso para evitarlos.",
    date: "7 julio 2025",
    category: "Estrategia",
    readTime: "10 min",
    publishDate: "2025-07-07",
  },
  {
    slug: "como-saber-si-mi-negocio-es-rentable",
    title: "Cómo saber si tu negocio es rentable de verdad",
    excerpt: "Facturar no es ganar. Indicadores clave de rentabilidad, punto de equilibrio y qué hacer si descubres que no eres rentable.",
    date: "21 julio 2025",
    category: "Rentabilidad",
    readTime: "10 min",
    publishDate: "2025-07-21",
  },
  {
    slug: "como-subir-precios-sin-perder-clientes",
    title: "Cómo subir precios sin perder clientes: guía para pymes",
    excerpt: "Cuándo es el momento, cómo comunicarlo y estrategias para que la subida de precios refuerce tu negocio.",
    date: "4 agosto 2025",
    category: "Rentabilidad",
    readTime: "10 min",
    publishDate: "2025-08-04",
  },
  {
    slug: "consultor-empresas-galicia-que-esperar",
    title: "Consultor de empresas en Galicia: qué esperar y cómo elegir bien",
    excerpt: "Qué puede hacer un consultor por tu negocio, qué preguntar antes de contratar y cómo sacarle el máximo partido.",
    date: "18 agosto 2025",
    category: "Estrategia",
    readTime: "10 min",
    publishDate: "2025-08-18",
  },
  {
    slug: "como-gestionar-empleados-pyme",
    title: "Cómo gestionar empleados en una pyme sin volverte loco",
    excerpt: "Contratar bien, dar feedback, gestionar conflictos y construir cultura de equipo en una empresa pequeña.",
    date: "1 septiembre 2025",
    category: "Organización",
    readTime: "10 min",
    publishDate: "2025-09-01",
  },
  {
    slug: "como-vender-mas-sin-bajar-precios",
    title: "Cómo vender más sin bajar precios",
    excerpt: "Bajar precios no es una estrategia. Vende más mejorando tu propuesta de valor, tu proceso comercial y tu seguimiento.",
    date: "15 septiembre 2025",
    category: "Clientes",
    readTime: "10 min",
    publishDate: "2025-09-15",
  },
  {
    slug: "plan-negocio-simple-una-pagina",
    title: "Plan de negocio en una página: lo único que necesitas",
    excerpt: "Olvida los planes de 50 páginas. Un plan práctico y actualizable cabe en una página. Te enseñamos cómo.",
    date: "6 octubre 2025",
    category: "Estrategia",
    readTime: "10 min",
    publishDate: "2025-10-06",
  },
  {
    slug: "automatizar-procesos-empresa-pequena",
    title: "Cómo automatizar procesos en una empresa pequeña",
    excerpt: "No necesitas ser grande para automatizar. Qué procesos priorizar, herramientas accesibles y errores a evitar.",
    date: "20 octubre 2025",
    category: "Organización",
    readTime: "10 min",
    publishDate: "2025-10-20",
  },
  {
    slug: "como-preparar-tu-empresa-para-crecer",
    title: "Cómo preparar tu empresa para crecer sin que se rompa por el camino",
    excerpt: "Crecer sin estructura es la receta para el caos. Cómo preparar tu empresa antes de dar el salto.",
    date: "3 noviembre 2025",
    category: "Crecimiento",
    readTime: "10 min",
    publishDate: "2025-11-03",
  },
  {
    slug: "como-analizar-tu-competencia",
    title: "Cómo analizar a tu competencia: guía práctica para pymes",
    excerpt: "Aprende a analizar a tu competencia de forma práctica para tomar mejores decisiones en tu negocio.",
    date: "17 noviembre 2025",
    category: "Estrategia",
    readTime: "10 min",
    publishDate: "2025-11-17",
  },
  {
    slug: "como-digitalizar-tu-negocio-pequeno",
    title: "Cómo digitalizar tu negocio pequeño sin complicarte",
    excerpt: "Digitalizar no es tener redes sociales. Es ordenar tu negocio con herramientas que ahorran tiempo y errores.",
    date: "1 diciembre 2025",
    category: "Organización",
    readTime: "10 min",
    publishDate: "2025-12-01",
  },
  {
    slug: "como-hacer-un-presupuesto-empresarial",
    title: "Cómo hacer un presupuesto empresarial: guía práctica para pymes",
    excerpt: "Un presupuesto no es una hoja de cálculo — es la herramienta que te dice si vas por buen camino o no.",
    date: "15 diciembre 2025",
    category: "Control y gestión",
    readTime: "10 min",
    publishDate: "2025-12-15",
  },
  {
    slug: "como-mejorar-el-flujo-de-caja",
    title: "Cómo mejorar el flujo de caja en tu negocio",
    excerpt: "El flujo de caja mata más empresas que la falta de ventas. Cómo controlarlo y mejorarlo desde hoy.",
    date: "12 enero 2026",
    category: "Control y gestión",
    readTime: "10 min",
    publishDate: "2026-01-12",
  },
  {
    slug: "como-motivar-equipo-trabajo-pyme",
    title: "Cómo motivar a tu equipo de trabajo en una pyme",
    excerpt: "La motivación no va de pizzas ni de futbolines. Va de claridad, autonomía y sentirse parte de algo.",
    date: "26 enero 2026",
    category: "Organización",
    readTime: "10 min",
    publishDate: "2026-01-26",
  },
  {
    slug: "cuando-cerrar-un-negocio",
    title: "Cuándo cerrar un negocio: señales que no debes ignorar",
    excerpt: "A veces la mejor decisión empresarial es cerrar. Cómo saber cuándo ha llegado ese momento.",
    date: "9 febrero 2026",
    category: "Estrategia",
    readTime: "10 min",
    publishDate: "2026-02-09",
  },
  {
    slug: "traspaso-generacional-empresa-familiar",
    title: "Traspaso generacional en la empresa familiar: cómo hacerlo bien",
    excerpt: "El 70 % de las empresas familiares no sobreviven al traspaso generacional. Cómo prepararlo para que la tuya sí.",
    date: "23 febrero 2026",
    category: "Estrategia",
    readTime: "10 min",
    publishDate: "2026-02-23",
  },
  {
    slug: "caso-exito-ferrados-transformacion-modelo-negocio",
    title: "Caso de éxito: cómo transformamos un blog con tráfico en un modelo de negocio rentable",
    excerpt: "Un portal con miles de visitas y cero ingresos. Así reconvertimos un proyecto informativo en un sistema de captación de leads para el sector forestal gallego.",
    date: "31 marzo 2026",
    category: "Caso de éxito",
    readTime: "12 min",
    publishDate: "2026-03-31",
  },
  {
    slug: "caso-exito-restaurante-rentabilidad",
    title: "Un restaurante que llenaba cada fin de semana y perdía dinero: qué encontramos y qué cambiamos",
    excerpt: "Caso real de un restaurante en Galicia que facturaba más de 10.000 € al mes y no conseguía ganar dinero. Escandallos, carta, turnos y proveedores: qué encontramos y qué cambiamos.",
    date: "4 abril 2026",
    category: "Caso de éxito",
    readTime: "12 min",
  },
  {
    slug: "redes-sociales-para-pymes",
    title: "Redes sociales para pymes: cuándo sirven, cuándo no y cuándo son una pérdida de tiempo",
    excerpt: "Análisis honesto sobre redes sociales para negocios pequeños. Cuándo invertir, cuándo no, errores que queman dinero y alternativas más rentables para captar clientes.",
    date: "4 abril 2026",
    category: "Marketing",
    readTime: "14 min",
  },
  {
    slug: "caso-exito-clinica-ocupacion-rentabilidad",
    title: "Caso de éxito: una clínica con agenda llena y rentabilidad baja",
    excerpt: "Caso real de una clínica en la provincia de A Coruña con buena ocupación pero márgenes muy bajos. Análisis de servicios, recall de pacientes y reorganización de precios.",
    date: "21 abril 2026",
    category: "Caso de éxito",
    readTime: "12 min",
  },
  {
    slug: "caso-exito-despacho-profesional-independiente",
    title: "Caso de éxito: un despacho profesional atrapado en el autoempleo",
    excerpt: "Caso real de un profesional independiente en A Coruña que facturaba pero no crecía. Segmentación de cartera, subida de tarifas, sistematización de procesos y salida del autoempleo.",
    date: "21 abril 2026",
    category: "Caso de éxito",
    readTime: "13 min",
  },
  {
    slug: "caso-exito-empresa-formacion-rentabilidad",
    title: "Caso de éxito: una empresa de formación que facturaba sin saber si ganaba dinero",
    excerpt: "Caso real de una empresa de formación en Galicia con 14 cursos activos y cero control de márgenes. Escandallo por curso, eliminación de líneas deficitarias y producto recurrente.",
    date: "21 abril 2026",
    category: "Caso de éxito",
    readTime: "13 min",
  },
  {
    slug: "caso-exito-tienda-barrio-rentabilidad",
    title: "Caso de éxito: una tienda de barrio que competía con el supermercado y ganó",
    excerpt: "Caso real de un comercio de alimentación de barrio en A Coruña presionado por la gran distribución. Diferenciación, mix de producto, precios y servicio.",
    date: "21 abril 2026",
    category: "Caso de éxito",
    readTime: "13 min",
  },
];

// Páginas principales del sitio para sitemap
export const STATIC_PAGES = [
  { path: "/", priority: 1.0, changeFrequency: "monthly" as const },
  { path: "/diagnostico-negocio", priority: 0.9, changeFrequency: "monthly" as const },
  { path: "/consultor-empresas-coruna", priority: 0.9, changeFrequency: "monthly" as const },
  { path: "/consultoria-empresarial-galicia", priority: 0.9, changeFrequency: "monthly" as const },
  { path: "/metodo-herramientas", priority: 0.8, changeFrequency: "monthly" as const },
  { path: "/experiencia-sectores-casos", priority: 0.7, changeFrequency: "monthly" as const },
  { path: "/colaboradores", priority: 0.7, changeFrequency: "monthly" as const },
  { path: "/blog", priority: 0.7, changeFrequency: "weekly" as const },
];

export function getVisiblePosts(today: string = new Date().toISOString().slice(0, 10)): BlogPost[] {
  return BLOG_POSTS.filter((p) => !p.publishDate || p.publishDate <= today);
}
