export type BlogPost = {
  slug: string;
  title: string;
  excerpt: string;
  date: string;
  category: string;
  readTime: string;
  isPillar?: boolean;
  publishDate?: string;
};

export const BLOG_POSTS: BlogPost[] = [
  // --- PILARES SEO ---
  {
    slug: "metodos-y-tiempos-para-pymes",
    title: "Métodos y tiempos para pymes: cómo aplicar principios de eficiencia operativa sin ser una fábrica",
    excerpt: "El estudio de métodos y tiempos tiene fama de ser cosa de ingenieros industriales con cronómetro en mano. En realidad, sus principios aplican perfectamente a un despacho, un restaurante o una tienda. Guía práctica con ejemplos reales en pymes no industriales.",
    date: "27 agosto 2026",
    category: "Organización",
    readTime: "12 min",
    publishDate: "2026-08-27",
  },
  {
    slug: "consultoria-administrativa-personalizada",
    title: "Consultoría administrativa personalizada: qué es, qué incluye y cuándo la necesita tu empresa",
    excerpt: "Consultoría administrativa personalizada no es más gestoría. Es poner orden real en cómo funciona tu empresa por dentro para dejar de perder tiempo y dinero por procesos rotos. Guía práctica con casos reales y diferencias con la gestoría.",
    date: "29 agosto 2026",
    category: "Organización",
    readTime: "12 min",
    publishDate: "2026-08-29",
  },
  {
    slug: "analisis-competitivo-empresas-coruna",
    title: "Análisis competitivo para empresas en A Coruña: cómo hacerlo bien sin gastar en informes que no lees",
    excerpt: "Análisis competitivo no es hacer un DAFO ni comprar un informe sectorial de 80 páginas. Es entender contra quién compites de verdad, qué hace bien y qué mal, y qué puedes aprovechar tú. Guía práctica adaptada al mercado de A Coruña.",
    date: "31 agosto 2026",
    category: "Estrategia",
    readTime: "10 min",
    publishDate: "2026-08-31",
  },
  {
    slug: "segmentacion-clientes-identificar-rentables",
    title: "Segmentación de clientes: cómo identificar a los rentables (y despedir a los tóxicos)",
    excerpt: "No todos tus clientes te dejan lo mismo. El 20% suele generar el 80% del beneficio — y otro 20% te hace perder dinero directamente. Guía práctica para segmentar tu cartera por rentabilidad real, con método, casos y cómo despedir clientes con elegancia.",
    date: "2 septiembre 2026",
    category: "Rentabilidad",
    readTime: "13 min",
    publishDate: "2026-09-02",
  },
  {
    slug: "aumentar-rentabilidad-asesoria-despacho-gestoria",
    title: "Cómo aumentar la rentabilidad de una asesoría, despacho o gestoría — Guía práctica",
    excerpt: "El sector de asesorías y gestorías vive una crisis silenciosa: clientes que se van a plataformas online, márgenes estancados y percepción de menos valor. Guía práctica con 6 palancas concretas, casos reales, errores típicos y plan de acción en 90 días.",
    date: "3 septiembre 2026",
    category: "Servicios profesionales",
    readTime: "16 min",
    isPillar: true,
    publishDate: "2026-09-03",
  },
  {
    slug: "como-mejorar-rentabilidad-empresa",
    title: "Cómo mejorar la rentabilidad de tu empresa — Guía completa para pymes",
    excerpt: "Guía pilar con todo lo que necesitas saber para mejorar la rentabilidad de tu pyme: márgenes, costes, precios, productividad, flujo de caja y un plan de acción paso a paso.",
    date: "10 abril 2025",
    category: "Rentabilidad",
    readTime: "18 min",
    isPillar: true,
  },
  {
    slug: "como-conseguir-clientes-para-tu-negocio",
    title: "Cómo conseguir más clientes para tu negocio — Guía completa de captación para pymes",
    excerpt: "Por qué falla la captación, canales reales, estrategia local vs digital, cómo crear un sistema estable, errores que tiran dinero y casos reales. Todo lo que una pyme necesita.",
    date: "10 abril 2025",
    category: "Clientes",
    readTime: "18 min",
    isPillar: true,
  },
  {
    slug: "indicadores-clave-de-una-empresa",
    title: "Qué números debe controlar cualquier empresa para no ir a ciegas — Guía completa de KPIs",
    excerpt: "Los 9 KPIs que toda pyme debe vigilar: margen, punto muerto, ticket medio, CAC, flujo de caja. Cómo interpretar datos, tomar decisiones con números reales y montar tu sistema de control mensual.",
    date: "10 abril 2025",
    category: "Control y gestión",
    readTime: "18 min",
    isPillar: true,
  },
  {
    slug: "como-organizar-empresa-pequena-salir-autoempleo",
    title: "Cómo organizar una empresa para que crezca (y dejar de ser esclavo de tu negocio) — Guía completa",
    excerpt: "Caos operativo, empresario autoempleado, procesos, delegación, sistemas simples, cómo liberar tiempo y preparar el crecimiento. Todo lo que una pyme necesita para dejar de depender del dueño.",
    date: "10 abril 2025",
    category: "Organización",
    readTime: "18 min",
    isPillar: true,
  },
  {
    slug: "como-hacer-crecer-una-empresa-pequena",
    title: "Cómo hacer crecer una empresa paso a paso — Guía completa de estrategia de crecimiento",
    excerpt: "Fases de crecimiento, errores al escalar, cuándo invertir, cuándo contratar, nuevas líneas de negocio, mentalidad empresarial y plan real de crecimiento para pymes.",
    date: "10 abril 2025",
    category: "Crecimiento",
    readTime: "18 min",
    isPillar: true,
  },
  {
    slug: "como-definir-estrategia-negocio",
    title: "Cómo definir la estrategia de tu negocio para dejar de improvisar — Guía completa",
    excerpt: "Modelo de negocio, propuesta de valor, posicionamiento, plan estratégico en una página, errores que cuestan dinero y revisión periódica. Todo lo que una pyme necesita para tener dirección.",
    date: "10 abril 2025",
    category: "Estrategia",
    readTime: "18 min",
    isPillar: true,
  },
  // --- ARTÍCULOS DE APOYO ---
  {
    slug: "por-que-no-funciona-la-publicidad-en-mi-negocio",
    title: "Por qué muchas empresas tiran el dinero en marketing (y cómo evitarlo)",
    excerpt: "Frustración con agencias, publicidad sin estrategia y dinero perdido. Descubre cómo saber si tu marketing funciona y un sistema práctico para evaluar cada euro que inviertes.",
    date: "13 marzo 2025",
    category: "Marketing",
    readTime: "12 min",
  },
  {
    slug: "como-diferenciarte-de-tu-competencia",
    title: "Cómo diferenciarte de tu competencia sin competir en precio",
    excerpt: "Si tu negocio ofrece lo mismo que los demás, compites por precio y pierdes margen. Descubre cómo encontrar tu ventaja competitiva real y posicionarte como la mejor opción.",
    date: "13 marzo 2025",
    category: "Estrategia",
    readTime: "13 min",
  },
  {
    slug: "como-fijar-precios-en-tu-negocio",
    title: "Cómo fijar precios en tu negocio sin perder clientes ni margen",
    excerpt: "La mayoría de pymes fijan precios por intuición o copiando a la competencia. Aprende métodos reales para calcular precios que cubran costes, generen beneficio y el cliente acepte.",
    date: "13 marzo 2025",
    category: "Rentabilidad",
    readTime: "14 min",
  },
  {
    slug: "problemas-de-liquidez-en-pymes",
    title: "Tu empresa factura pero no tiene dinero: cómo resolver los problemas de liquidez",
    excerpt: "Facturas pendientes, pagos que no cuadran y la cuenta siempre al límite. Causas reales de los problemas de liquidez en pymes y un plan práctico para resolverlos.",
    date: "13 marzo 2025",
    category: "Control y gestión",
    readTime: "13 min",
  },
  {
    slug: "como-tomar-decisiones-en-un-negocio",
    title: "Las decisiones que están frenando tu negocio (aunque no te des cuenta)",
    excerpt: "Soledad, miedo, decisiones emocionales y falta de claridad estratégica. Descubre qué bloquea a los empresarios y cómo aprender a pensar con método para desbloquear tu negocio.",
    date: "13 marzo 2025",
    category: "Estrategia",
    readTime: "13 min",
  },
  {
    slug: "como-mejorar-rentabilidad-restaurante-bar",
    title: "Cómo mejorar la rentabilidad de tu restaurante o bar sin subir precios",
    excerpt: "Escandallos, costes ocultos, turnos, carta y proveedores. Guía práctica para que tu restaurante o bar gane más dinero optimizando lo que ya tienes.",
    date: "13 marzo 2025",
    category: "Rentabilidad",
    readTime: "14 min",
  },
  {
    slug: "cuando-contratar-un-consultor-de-negocios",
    title: "¿Cuándo merece la pena contratar un consultor de negocios?",
    excerpt: "Señales claras de que tu negocio necesita una mirada externa, qué esperar de una consultoría, cuánto cuesta y cómo elegir al consultor adecuado sin tirar el dinero.",
    date: "13 marzo 2025",
    category: "Estrategia",
    readTime: "12 min",
  },
  {
    slug: "por-que-tu-empresa-factura-pero-no-gana-dinero",
    title: "Por qué tu empresa factura pero no gana dinero",
    excerpt: "Errores habituales que destruyen la rentabilidad de las pymes, cómo calcular si tu negocio realmente gana dinero y decisiones que mejoran los beneficios rápidamente.",
    date: "13 marzo 2025",
    category: "Rentabilidad",
    readTime: "12 min",
  },
  // --- ARTÍCULOS LONG TAIL (publicación programada) ---
  {
    slug: "como-reducir-gastos-empresa-sin-recortar",
    title: "Cómo reducir gastos en tu empresa sin recortar en lo que importa",
    excerpt: "7 áreas donde las pymes malgastan dinero y cómo optimizar gastos sin cargarte la calidad ni el crecimiento.",
    date: "21 abril 2025",
    category: "Rentabilidad",
    readTime: "10 min",
    publishDate: "2025-04-21",
  },
  {
    slug: "mi-negocio-no-crece-que-hago",
    title: "Mi negocio no crece: qué hacer cuando te estancas",
    excerpt: "Señales de estancamiento, causas reales y 5 acciones concretas para salir del bloqueo y volver a crecer.",
    date: "24 abril 2025",
    category: "Crecimiento",
    readTime: "10 min",
    publishDate: "2025-04-24",
  },
  {
    slug: "cuanto-debe-ganar-el-dueno-de-un-negocio",
    title: "Cuánto debe ganar el dueño de un negocio: la pregunta incómoda",
    excerpt: "Muchos empresarios cobran menos que sus empleados. Cómo calcular tu sueldo justo y separar beneficio de compensación.",
    date: "5 mayo 2025",
    category: "Rentabilidad",
    readTime: "10 min",
    publishDate: "2025-05-05",
  },
  {
    slug: "como-delegar-tareas-sin-perder-control",
    title: "Cómo delegar tareas en tu empresa sin perder el control",
    excerpt: "Por qué no delegas, qué te cuesta no hacerlo, qué delegar primero y cómo montar un sistema de delegación real.",
    date: "19 mayo 2025",
    category: "Organización",
    readTime: "10 min",
    publishDate: "2025-05-19",
  },
  {
    slug: "como-calcular-margen-beneficio-producto",
    title: "Cómo calcular el margen de beneficio de un producto o servicio",
    excerpt: "Margen bruto vs neto, fórmulas claras, los costes que nadie incluye y qué hacer cuando un producto tiene margen negativo.",
    date: "2 junio 2025",
    category: "Rentabilidad",
    readTime: "10 min",
    publishDate: "2025-06-02",
  },
  {
    slug: "como-fidelizar-clientes-pyme",
    title: "Cómo fidelizar clientes en una pyme: estrategias que funcionan",
    excerpt: "Retener clientes cuesta 5 veces menos que conseguir nuevos. Estrategias prácticas de fidelización para pymes.",
    date: "16 junio 2025",
    category: "Clientes",
    readTime: "10 min",
    publishDate: "2025-06-16",
  },
  {
    slug: "errores-empresarios-pyme-mas-comunes",
    title: "Los 10 errores más comunes de los empresarios pyme",
    excerpt: "Los fallos de gestión que frenan a la mayoría de pymes. Identificarlos es el primer paso para evitarlos.",
    date: "7 julio 2025",
    category: "Estrategia",
    readTime: "10 min",
    publishDate: "2025-07-07",
  },
  {
    slug: "como-saber-si-mi-negocio-es-rentable",
    title: "Cómo saber si tu negocio es rentable de verdad",
    excerpt: "Facturar no es ganar. Indicadores clave de rentabilidad, punto de equilibrio y qué hacer si descubres que no eres rentable.",
    date: "21 julio 2025",
    category: "Rentabilidad",
    readTime: "10 min",
    publishDate: "2025-07-21",
  },
  {
    slug: "como-subir-precios-sin-perder-clientes",
    title: "Cómo subir precios sin perder clientes: guía para pymes",
    excerpt: "Cuándo es el momento, cómo comunicarlo y estrategias para que la subida de precios refuerce tu negocio.",
    date: "4 agosto 2025",
    category: "Rentabilidad",
    readTime: "10 min",
    publishDate: "2025-08-04",
  },
  {
    slug: "consultor-empresas-galicia-que-esperar",
    title: "Consultor de empresas en Galicia: qué esperar y cómo elegir bien",
    excerpt: "Qué puede hacer un consultor por tu negocio, qué preguntar antes de contratar y cómo sacarle el máximo partido.",
    date: "18 agosto 2025",
    category: "Estrategia",
    readTime: "10 min",
    publishDate: "2025-08-18",
  },
  {
    slug: "como-gestionar-empleados-pyme",
    title: "Cómo gestionar empleados en una pyme sin volverte loco",
    excerpt: "Contratar bien, dar feedback, gestionar conflictos y construir cultura de equipo en una empresa pequeña.",
    date: "1 septiembre 2025",
    category: "Organización",
    readTime: "10 min",
    publishDate: "2025-09-01",
  },
  {
    slug: "como-vender-mas-sin-bajar-precios",
    title: "Cómo vender más sin bajar precios",
    excerpt: "Bajar precios no es una estrategia. Vende más mejorando tu propuesta de valor, tu proceso comercial y tu seguimiento.",
    date: "15 septiembre 2025",
    category: "Ventas",
    readTime: "10 min",
    publishDate: "2025-09-15",
  },
  {
    slug: "plan-negocio-simple-una-pagina",
    title: "Plan de negocio en una página: lo único que necesitas",
    excerpt: "Olvida los planes de 50 páginas. Un plan práctico y actualizable cabe en una página. Te enseñamos cómo.",
    date: "6 octubre 2025",
    category: "Estrategia",
    readTime: "10 min",
    publishDate: "2025-10-06",
  },
  {
    slug: "automatizar-procesos-empresa-pequena",
    title: "Cómo automatizar procesos en una empresa pequeña",
    excerpt: "No necesitas ser grande para automatizar. Qué procesos priorizar, herramientas accesibles y errores a evitar.",
    date: "20 octubre 2025",
    category: "Organización",
    readTime: "10 min",
    publishDate: "2025-10-20",
  },
  {
    slug: "como-preparar-tu-empresa-para-crecer",
    title: "Cómo preparar tu empresa para crecer sin que se rompa por el camino",
    excerpt: "Crecer sin estructura es la receta para el caos. Cómo preparar tu empresa antes de dar el salto.",
    date: "3 noviembre 2025",
    category: "Crecimiento",
    readTime: "10 min",
    publishDate: "2025-11-03",
  },
  {
    slug: "como-analizar-tu-competencia",
    title: "Cómo analizar a tu competencia: guía práctica para pymes",
    excerpt: "Aprende a analizar a tu competencia de forma práctica para tomar mejores decisiones en tu negocio.",
    date: "17 noviembre 2025",
    category: "Estrategia",
    readTime: "10 min",
    publishDate: "2025-11-17",
  },
  {
    slug: "como-digitalizar-tu-negocio-pequeno",
    title: "Cómo digitalizar tu negocio pequeño sin complicarte",
    excerpt: "Digitalizar no es tener redes sociales. Es ordenar tu negocio con herramientas que ahorran tiempo y errores.",
    date: "1 diciembre 2025",
    category: "Organización",
    readTime: "10 min",
    publishDate: "2025-12-01",
  },
  {
    slug: "como-hacer-un-presupuesto-empresarial",
    title: "Cómo hacer un presupuesto empresarial: guía práctica para pymes",
    excerpt: "Un presupuesto no es una hoja de cálculo — es la herramienta que te dice si vas por buen camino o no.",
    date: "15 diciembre 2025",
    category: "Control y gestión",
    readTime: "10 min",
    publishDate: "2025-12-15",
  },
  {
    slug: "como-mejorar-el-flujo-de-caja",
    title: "Cómo mejorar el flujo de caja en tu negocio",
    excerpt: "El flujo de caja mata más empresas que la falta de ventas. Cómo controlarlo y mejorarlo desde hoy.",
    date: "12 enero 2026",
    category: "Control y gestión",
    readTime: "10 min",
    publishDate: "2026-01-12",
  },
  {
    slug: "como-motivar-equipo-trabajo-pyme",
    title: "Cómo motivar a tu equipo de trabajo en una pyme",
    excerpt: "La motivación no va de pizzas ni de futbolines. Va de claridad, autonomía y sentirse parte de algo.",
    date: "26 enero 2026",
    category: "Organización",
    readTime: "10 min",
    publishDate: "2026-01-26",
  },
  {
    slug: "cuando-cerrar-un-negocio",
    title: "Cuándo cerrar un negocio: señales que no debes ignorar",
    excerpt: "A veces la mejor decisión empresarial es cerrar. Cómo saber cuándo ha llegado ese momento.",
    date: "9 febrero 2026",
    category: "Estrategia",
    readTime: "10 min",
    publishDate: "2026-02-09",
  },
  {
    slug: "traspaso-generacional-empresa-familiar",
    title: "Traspaso generacional en la empresa familiar: cómo hacerlo bien",
    excerpt: "El 70 % de las empresas familiares no sobreviven al traspaso generacional. Cómo prepararlo para que la tuya sí.",
    date: "23 febrero 2026",
    category: "Estrategia",
    readTime: "10 min",
    publishDate: "2026-02-23",
  },
  {
    slug: "caso-exito-ferrados-transformacion-modelo-negocio",
    title: "Caso de éxito: cómo transformamos un blog con tráfico en un modelo de negocio rentable",
    excerpt: "Un portal con miles de visitas y cero ingresos. Así reconvertimos un proyecto informativo en un sistema de captación de leads para el sector forestal gallego.",
    date: "31 marzo 2026",
    category: "Caso de éxito",
    readTime: "12 min",
    publishDate: "2026-03-31",
  },
  {
    slug: "caso-exito-restaurante-rentabilidad",
    title: "Un restaurante que llenaba cada fin de semana y perdía dinero: qué encontramos y qué cambiamos",
    excerpt: "Caso real de un restaurante en Galicia que facturaba más de 10.000 € al mes y no conseguía ganar dinero. Escandallos, carta, turnos y proveedores: qué encontramos y qué cambiamos.",
    date: "4 abril 2026",
    category: "Caso de éxito",
    readTime: "12 min",
  },
  {
    slug: "redes-sociales-para-pymes",
    title: "Redes sociales para pymes: cuándo sirven, cuándo no y cuándo son una pérdida de tiempo",
    excerpt: "Análisis honesto sobre redes sociales para negocios pequeños. Cuándo invertir, cuándo no, errores que queman dinero y alternativas más rentables para captar clientes.",
    date: "4 abril 2026",
    category: "Marketing",
    readTime: "14 min",
  },
  {
    slug: "caso-exito-clinica-ocupacion-rentabilidad",
    title: "Caso de éxito: una clínica con agenda llena y rentabilidad baja",
    excerpt: "Caso real de una clínica en la provincia de A Coruña con buena ocupación pero márgenes muy bajos. Análisis de servicios, recall de pacientes y reorganización de precios.",
    date: "21 abril 2026",
    category: "Caso de éxito",
    readTime: "12 min",
  },
  {
    slug: "caso-exito-despacho-profesional-independiente",
    title: "Caso de éxito: un despacho profesional atrapado en el autoempleo",
    excerpt: "Caso real de un profesional independiente en A Coruña que facturaba pero no crecía. Segmentación de cartera, subida de tarifas, sistematización de procesos y salida del autoempleo.",
    date: "21 abril 2026",
    category: "Caso de éxito",
    readTime: "13 min",
  },
  {
    slug: "caso-exito-empresa-formacion-rentabilidad",
    title: "Caso de éxito: una empresa de formación que facturaba sin saber si ganaba dinero",
    excerpt: "Caso real de una empresa de formación en Galicia con 14 cursos activos y cero control de márgenes. Escandallo por curso, eliminación de líneas deficitarias y producto recurrente.",
    date: "21 abril 2026",
    category: "Caso de éxito",
    readTime: "13 min",
  },
  {
    slug: "caso-exito-tienda-barrio-rentabilidad",
    title: "Caso de éxito: una tienda de barrio que competía con el supermercado y ganó",
    excerpt: "Caso real de un comercio de alimentación de barrio en A Coruña presionado por la gran distribución. Diferenciación, mix de producto, precios y servicio.",
    date: "21 abril 2026",
    category: "Caso de éxito",
    readTime: "13 min",
  },
  {
    slug: "consultor-empresas-a-coruna-guia",
    title: "Consultor de empresas en A Coruña: guía para pymes que buscan ayuda real",
    excerpt: "Qué esperar de un consultor de empresas en A Coruña, cuánto cuesta, cómo elegir bien y en qué se diferencia de una gestoría. Guía local para pymes.",
    date: "21 abril 2026",
    category: "Estrategia",
    readTime: "11 min",
  },
  {
    slug: "retos-pymes-galicia-2026",
    title: "Retos de las pymes en Galicia en 2026: lo que tienes que mirar este año",
    excerpt: "Los 6 retos que marcarán la rentabilidad de las pymes gallegas en 2026: costes, relevo generacional, digitalización, talento, competencia y complejidad interna.",
    date: "22 abril 2026",
    category: "Estrategia",
    readTime: "12 min",
  },
  {
    slug: "hosteleria-coruna-rentabilidad",
    title: "Hostelería en A Coruña: cómo ser rentable en un mercado cada vez más difícil",
    excerpt: "Análisis práctico de la rentabilidad en la hostelería de A Coruña: costes, estacionalidad, escandallos, cartas y competencia. Guía para bares, cafeterías y restaurantes.",
    date: "22 abril 2026",
    category: "Rentabilidad",
    readTime: "12 min",
  },
  {
    slug: "emprender-galicia-errores",
    title: "Emprender en Galicia: los 8 errores que hacen que el 50 % de los negocios cierre antes de 5 años",
    excerpt: "Los errores más frecuentes al emprender en Galicia y cómo evitarlos. Viabilidad, costes, precios, estacionalidad y estructura. Guía para emprendedores gallegos.",
    date: "22 abril 2026",
    category: "Estrategia",
    readTime: "13 min",
  },
  // --- ARTÍCULOS PROGRAMADOS (publicación escalonada mayo–julio 2026) ---
  {
    slug: "como-hacer-proceso-comercial-pyme",
    title: "Cómo montar un proceso comercial en tu pyme (aunque no seas vendedor)",
    excerpt: "Define tu cliente ideal, crea un pipeline simple, monta un sistema de seguimiento y mide resultados. Proceso comercial práctico para pymes.",
    date: "25 mayo 2026",
    category: "Ventas",
    readTime: "11 min",
    publishDate: "2026-05-25",
  },
  {
    slug: "cuanto-cuesta-realmente-un-empleado",
    title: "Cuánto cuesta realmente un empleado (y cómo calcularlo)",
    excerpt: "Un salario de 1.500 € brutos cuesta en realidad 2.800–3.200 € al mes. Seguridad Social, vacaciones, herramientas, formación y tiempo de gestión.",
    date: "28 mayo 2026",
    category: "Control y gestión",
    readTime: "10 min",
    publishDate: "2026-05-28",
  },
  {
    slug: "que-hacer-cuando-cliente-importante-te-deja",
    title: "Qué hacer cuando un cliente importante te deja",
    excerpt: "Plan de acción inmediato, impacto en tesorería, regla del 20 % de concentración y estrategias de diversificación para que no vuelva a pasar.",
    date: "1 junio 2026",
    category: "Clientes",
    readTime: "11 min",
    publishDate: "2026-06-01",
  },
  {
    slug: "como-saber-si-tu-marketing-funciona",
    title: "Cómo saber si tu marketing está funcionando: métricas para pymes",
    excerpt: "CAC, tasa de conversión, ROI por campaña y coste por lead. Las 4 métricas que toda pyme debe controlar para no tirar dinero en marketing.",
    date: "4 junio 2026",
    category: "Marketing",
    readTime: "11 min",
    publishDate: "2026-06-04",
  },
  {
    slug: "mi-empresa-depende-de-mi",
    title: "Mi empresa depende de mí: cómo salir de la trampa",
    excerpt: "Síntomas de dependencia del dueño, cuánto te cuesta y un plan de 5 pasos para liberar tu empresa de ti mismo.",
    date: "8 junio 2026",
    category: "Organización",
    readTime: "12 min",
    publishDate: "2026-06-08",
  },
  {
    slug: "como-negociar-con-proveedores",
    title: "Cómo negociar con proveedores cuando eres pequeño",
    excerpt: "6 tácticas de negociación para pymes con poco poder de compra. Consolidar, negociar condiciones, usar la competencia y construir relación.",
    date: "11 junio 2026",
    category: "Rentabilidad",
    readTime: "11 min",
    publishDate: "2026-06-11",
  },
  {
    slug: "como-captar-clientes-negocio-local",
    title: "Cómo captar clientes en un negocio local sin tirar dinero",
    excerpt: "Google My Business, SEO local, alianzas, referidos y micro-eventos. Los canales que realmente funcionan para negocios de proximidad.",
    date: "15 junio 2026",
    category: "Marketing",
    readTime: "11 min",
    publishDate: "2026-06-15",
  },
  {
    slug: "caso-exito-gimnasio-coruna-precio",
    title: "Caso de éxito: un gimnasio en Coruña que dejó de competir por precio",
    excerpt: "De 380 socios a 29 €/mes peleando con low-cost, a 220 socios a 59 €/mes con entrenamiento especializado. Reposicionamiento, precios y fidelización.",
    date: "18 junio 2026",
    category: "Caso de éxito",
    readTime: "12 min",
    publishDate: "2026-06-18",
  },
  {
    slug: "como-montar-sistema-cobros",
    title: "Cómo montar un sistema de cobros que funcione",
    excerpt: "Condiciones claras, recordatorios automáticos, escalado de reclamación y descuentos por pronto pago. Sistema práctico para pymes.",
    date: "22 junio 2026",
    category: "Control y gestión",
    readTime: "10 min",
    publishDate: "2026-06-22",
  },
  {
    slug: "por-que-tu-web-no-trae-clientes",
    title: "Por qué tu web no te trae clientes (y qué hacer)",
    excerpt: "7 errores habituales en webs de pymes y 7 soluciones rápidas. Cuándo necesitas un rediseño y cuándo basta con contenido y SEO.",
    date: "25 junio 2026",
    category: "Marketing",
    readTime: "11 min",
    publishDate: "2026-06-25",
  },
  {
    slug: "como-vender-servicios-profesionales",
    title: "Cómo vender servicios profesionales sin sentirte vendedor",
    excerpt: "Vender es ayudar a decidir. Enfoque basado en confianza: compartir conocimiento, diagnosticar antes de proponer, presentar opciones.",
    date: "29 junio 2026",
    category: "Ventas",
    readTime: "12 min",
    publishDate: "2026-06-29",
  },
  {
    slug: "caso-exito-empresa-servicios-tecnicos-margen",
    title: "Caso de éxito: una empresa de servicios técnicos que duplicó su margen",
    excerpt: "De 15 % a 32 % de margen bruto con escandallo por trabajo, tarifa triple, pedido mínimo y contratos de mantenimiento recurrente.",
    date: "2 julio 2026",
    category: "Caso de éxito",
    readTime: "12 min",
    publishDate: "2026-07-02",
  },
  {
    slug: "como-crear-oferta-irresistible",
    title: "Cómo crear una oferta irresistible para tu negocio",
    excerpt: "Resultado claro, reversión de riesgo, urgencia real y bonificaciones que suman valor. Anatomía de una oferta que se vende sola.",
    date: "6 julio 2026",
    category: "Ventas",
    readTime: "11 min",
    publishDate: "2026-07-06",
  },
  {
    slug: "coste-de-no-tomar-decisiones",
    title: "El coste de no tomar decisiones en tu empresa",
    excerpt: "La parálisis por análisis cuesta más que una decisión equivocada. Costes ocultos, regla del 70 % y marcos para decidir más rápido.",
    date: "9 julio 2026",
    category: "Estrategia",
    readTime: "12 min",
    publishDate: "2026-07-09",
  },
  {
    slug: "como-hacer-seguimiento-comercial",
    title: "Cómo hacer seguimiento comercial sin ser pesado",
    excerpt: "El 80 % de las ventas se cierran después del quinto contacto. Cadencia, canales, plantillas y CRM mínimo viable para pymes.",
    date: "13 julio 2026",
    category: "Ventas",
    readTime: "11 min",
    publishDate: "2026-07-13",
  },
  {
    slug: "google-my-business-negocios-locales",
    title: "Google My Business para negocios locales: guía práctica",
    excerpt: "Optimiza tu ficha de Google paso a paso: categorías, fotos, reseñas, publicaciones y conexión con SEO local. Los negocios optimizados reciben 7× más clics.",
    date: "16 julio 2026",
    category: "Marketing",
    readTime: "12 min",
    publishDate: "2026-07-16",
  },
  {
    slug: "como-revisar-si-tu-negocio-va-bien",
    title: "Cómo revisar si tu negocio va bien: el check-up trimestral",
    excerpt: "Plantilla de revisión trimestral en 5 áreas: finanzas, comercial, operaciones, equipo y estrategia. Sistema de puntuación y señales de alerta.",
    date: "20 julio 2026",
    category: "Control y gestión",
    readTime: "11 min",
    publishDate: "2026-07-20",
  },
  {
    slug: "caso-exito-comercio-rural-galicia-nicho-online",
    title: "Caso de éxito: un comercio rural en Galicia que encontró su nicho online",
    excerpt: "De 100 % venta local a 45 % online con cestas gourmet gallegas. Tienda online sencilla, Google My Business y alianzas con turismo rural.",
    date: "23 julio 2026",
    category: "Caso de éxito",
    readTime: "12 min",
    publishDate: "2026-07-23",
  },
  {
    slug: "cuando-contratar-primer-empleado",
    title: "Cuándo y cómo contratar a tu primer empleado",
    excerpt: "Señales de que estás listo, checklist financiero (6 meses de colchón), cómo definir el puesto y errores que te costarán caro.",
    date: "27 julio 2026",
    category: "Crecimiento",
    readTime: "11 min",
    publishDate: "2026-07-27",
  },
  {
    slug: "como-dejar-de-competir-por-precio",
    title: "Cómo dejar de competir por precio: estrategia de valor para pymes",
    excerpt: "La escalera de valor: de commodity a transformación. Nichos, paquetes, capa de expertise y costes de cambio. Sal de la guerra de precios.",
    date: "30 julio 2026",
    category: "Ventas",
    readTime: "12 min",
    publishDate: "2026-07-30",
  },
];

// Páginas principales del sitio para sitemap
export const STATIC_PAGES = [
  { path: "/", priority: 1.0, changeFrequency: "monthly" as const },
  { path: "/servicios", priority: 0.9, changeFrequency: "monthly" as const },
  { path: "/diagnostico-negocio", priority: 0.9, changeFrequency: "monthly" as const },
  { path: "/consultor-empresas-coruna", priority: 0.9, changeFrequency: "monthly" as const },
  { path: "/consultor-empresas-lugo", priority: 0.85, changeFrequency: "monthly" as const },
  { path: "/consultor-empresas-ourense", priority: 0.85, changeFrequency: "monthly" as const },
  { path: "/consultor-empresas-pontevedra", priority: 0.85, changeFrequency: "monthly" as const },
  { path: "/consultoria-empresarial-galicia", priority: 0.9, changeFrequency: "monthly" as const },
  { path: "/metodo-herramientas", priority: 0.8, changeFrequency: "monthly" as const },
  { path: "/experiencia-sectores-casos", priority: 0.7, changeFrequency: "monthly" as const },
  { path: "/colaboradores", priority: 0.7, changeFrequency: "monthly" as const },
  { path: "/blog", priority: 0.7, changeFrequency: "weekly" as const },
  { path: "/consultoria-hosteleria-restauracion", priority: 0.8, changeFrequency: "monthly" as const },
  { path: "/consultoria-comercio-retail", priority: 0.8, changeFrequency: "monthly" as const },
  { path: "/consultoria-servicios-profesionales", priority: 0.8, changeFrequency: "monthly" as const },
  { path: "/consultoria-salud-bienestar", priority: 0.8, changeFrequency: "monthly" as const },
  { path: "/consultoria-formacion-turismo-eventos", priority: 0.8, changeFrequency: "monthly" as const },
  { path: "/coaching-empresarial-coruna-galicia", priority: 0.85, changeFrequency: "monthly" as const },
  { path: "/aviso-legal", priority: 0.3, changeFrequency: "yearly" as const },
  { path: "/politica-privacidad", priority: 0.3, changeFrequency: "yearly" as const },
  { path: "/politica-cookies", priority: 0.3, changeFrequency: "yearly" as const },
];

export function getVisiblePosts(today: string = new Date().toISOString().slice(0, 10)): BlogPost[] {
  return BLOG_POSTS.filter((p) => !p.publishDate || p.publishDate <= today);
}

const MONTHS_ES: Record<string, string> = {
  enero: "01", febrero: "02", marzo: "03", abril: "04",
  mayo: "05", junio: "06", julio: "07", agosto: "08",
  septiembre: "09", octubre: "10", noviembre: "11", diciembre: "12",
};

function postSortDate(post: BlogPost): string {
  if (post.publishDate) return post.publishDate;
  // Parseo del texto "10 abril 2025" → "2025-04-10"
  const parts = post.date.toLowerCase().split(" ");
  if (parts.length === 3) {
    const [day, monthName, year] = parts;
    const month = MONTHS_ES[monthName];
    if (month && /^\d{4}$/.test(year)) {
      return `${year}-${month}-${day.padStart(2, "0")}`;
    }
  }
  return "2000-01-01";
}

export function getLatestPosts(
  limit: number = 8,
  today: string = new Date().toISOString().slice(0, 10)
): BlogPost[] {
  return getVisiblePosts(today)
    .slice()
    .sort((a, b) => postSortDate(b).localeCompare(postSortDate(a)))
    .slice(0, limit);
}
